apiVersion: v1
kind: Pod
spec:
  serviceAccountName: hadoop-submitter
  containers:
    - name: sonar-scanner
      image: sonarsource/sonar-scanner-cli:latest
      command: ["cat"]
      tty: true
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          memory: 3Gi
    # ref: https://plugins.jenkins.io/kubernetes/
    - name: gcloud
      image: gcr.io/google.com/cloudsdktool/google-cloud-cli:stable
      command: ["cat"]
      tty: true
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          memory: 2Gi
